### ISSUE TITLE
Error at agent start

### ISSUE THREAD

**Issue by andrewskorik** [marionettejs/marionette.inspector#310] opened 2016-06-13 15:30 UTC
Looks like deprecated functionality was removed from Marionette, but leaved in inspector agent code 
`Agent.patchMarionetteModule(Marionette.Module);`
This line generates error

**Comment by paulfalgout** [comment] 2016-06-13 17:41
Currently the inspector only supports Marionette v2.  v3 will be considered after its release.

**Comment by andrewskorik** [comment] 2016-06-13 18:40
I use 2.4.7 and already understood I was wrong about reason, Marionette.Module definition exist in code but undefined at 
`Agent.patchMarionetteModule(Marionette.Module);`
Marionette.Application already defined at the same time.. And patching of Backbone view also works before.. Looks like the inspector code has some difficulties with Marionette initialization order.
In sample I not using any kind of module loaders, just injecting scripts with useref and using browser sync. From log looks like page initialized correctly at first time and reloaded after connecting inspector and it has error with patching Module component. Without ispector all works as expected.
Order of inculed scripts
`
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/underscore/underscore.js"></script>
<script src="bower_components/backbone/backbone.js"></script>
<script src="bower_components/backbone.babysitter/lib/backbone.babysitter.js"></script>
<script src="bower_components/backbone.wreqr/lib/backbone.wreqr.js"></script>
<script src="bower_components/backbone.marionette/lib/core/backbone.marionette.js"></script>


<script src="/js/namespace.js"></script>
<script src="/js/main.js"></script>

`

**Comment by Ogrynko** [comment] 2016-06-19 18:44
Have got exactly the same issue in v2.4.7! 
I'm using Webpack modules and have included the following before Marionette is used:

```javascript
if (window.__agent) {
    window.__agent.start(Backbone, Marionette);
}
```

However the problem is the same: `Marionette` instance exists, but `Marionette.Module` is undefined, thus firing an error in `patchMarionetteModule` function.

**Comment by lddubeau** [comment] 2016-07-25 13:29
I've run into the same issue with Marionette v2.4.7. I'm using RequireJS in my application.

### Workarounds

#### Export `Marionette` to `Backbone` once `Marionette` is fully defined.

If I edit `backbone.marionette.js` so that `Backbone.Marionette = Marionette` is done once, and only once, just before returning `Marionette` from the factory, the error goes away.

#### Don't leak `Backbone`.

If I edit `backbone.js` (or the `.min` equivalent) so that the AMD path does not leak `Backbone` to the global space, then the error goes away. As mentioned in the documentation I do use:

```
if (window.__agent) {
    window.__agent.start(Backbone, Marionette);
}
```

Some non-AMD-aware extensions to Backbone need to have `Backbone` in the global space. So this is not viable in all cases.

### Observations

The inspector fails because `Marionette.Module` is undefined but if I remove the inspector from my Chrome extensions and then check `Marionette`, `Marionette.Module` is defined. What gives?

I believe the problem is due to these factors:

1. `backbone.js`, even when using the AMD path, leaks the `Backbone` symbol into the global space.

2. Marionette installs itself as `Backbone.Marionette`, and then constructs itself. So the value assigned to `Backbone.Marionette` changes while Marionette is constructing itself.

3. The inspector's cleverness causes it to shoot itself in the foot. It watches the global space for the appearance of `Backbone`, which happens when Backbone is loaded, then it checks for changes to `Backbone` and its properties. One change is that Marionette adds itself as `Backbone.Marionette` and it progressively modifies itself. This sequence of changes eventually causes the inspector to try to patch Marionette *while Marionette is constructing itself*.

**Comment by blikblum** [comment] 2017-02-18 15:28
Any live, public example so i can look at it?

**Closed** 2017-02-23 06:13 UTC
